name: Cleanup Pull Request after close

# only trigger on pull request closed events
on:
  pull_request:
    types: [ closed ]

jobs:
  declutter:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Run declutter action
      uses: Confectrician/post-pr-declutter@v0.1
      with:
        repo-token: "${{ github.token }}"
        close-reason: github.event.pull_request.merged
